# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('telefoonNr', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('bericht', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Klassen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('numeriekeCode', models.CharField(max_length=100)),
                ('richting', models.CharField(max_length=100)),
                ('leeraar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leraren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('voornaam', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('klassen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Klassen')),
            ],
        ),
        migrations.CreateModel(
            name='Richtingen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('omschrijving', models.CharField(max_length=255)),
                ('klassen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Klassen')),
            ],
        ),
    ]
